### PR TITLE
Publish Microsoft Authored templates to azure samples browser

### PR DESCRIPTION
**Pull request by zedy-wj**
Publish `openai-plugin-fastapi` template to azure samples browser.

@rajeshkamal5050, @hemarina for notification.

### CODE REVIEW

**Review by hemarina — APPROVED** [review]
LGTM. @digitarald for notification. Could you review this PR?

**Comment by v-xuto** [comment]
@digitarald Could you help review this PR and merge it if it looks good?

**Comment by digitarald** [comment]
Checking how far we want to have this repo spread as example.

**Comment by hemarina** [comment]
@zedy-wj Could you close this PR? Had an offline chat with Harald and Jon. This was a demo repo for Build. There's currently no maintainer and owner of this repo. We'll not add it to learning page.

**Comment by zedy-wj** [comment]
@hemarina  sure, closed it.

**Pull request closed without merging**
